// ==========================================
// NEW MATCH SETUP (client/src/pages/NewMatch.jsx)
// ==========================================
import React, { useState, useEffect } from 'react';
import { Container, Row, Col, Card, Form, Button, Alert, Spinner } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

const NewMatch = () => {
  // 1. Define our State variables
  const [teams, setTeams] = useState([]); // Will hold the list of teams from the database
  const [isLoading, setIsLoading] = useState(true); // Controls the loading spinner
  const [error, setError] = useState('');

  // Form input states
  const [homeTeamId, setHomeTeamId] = useState('');
  const [awayTeamId, setAwayTeamId] = useState('');
  const [tournamentName, setTournamentName] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const navigate = useNavigate();

  // 2. Fetch Teams when the page loads
  // The empty array [] at the end means "only run this once when the component mounts"
  useEffect(() => {
    const fetchTeams = async () => {
      try {
        const response = await axios.get('/api/teams');
        setTeams(response.data.teams);
        
        // If we have teams, automatically set the first team as the default dropdown option
        if (response.data.teams.length > 0) {
          setHomeTeamId(response.data.teams[0].id);
          // Try to set the second team as the away team if it exists
          if (response.data.teams.length > 1) {
            setAwayTeamId(response.data.teams[1].id);
          }
        }
      } catch (err) {
        console.error("Failed to load teams", err);
        setError("Failed to load teams from the database.");
      } finally {
        setIsLoading(false);
      }
    };

    fetchTeams();
  }, []);

  // 3. Handle Form Submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    // Prevent selecting the same team for both home and away
    if (homeTeamId === awayTeamId) {
      setError("A team cannot play against itself. Please select different teams.");
      return;
    }

    setIsSubmitting(true);

    try {
      // Send the data to our Node.js API to create the Match container
      const response = await axios.post('/api/matches', {
        homeTeamId: homeTeamId,
        awayTeamId: awayTeamId,
        tournamentName: tournamentName || "Friendly Match"
      });

      // Extract the new Match ID generated by the database
      const newMatchId = response.data.match.id;

      // Instantly redirect the coach to the Live Touchline Dashboard for this specific match
      navigate(`/live-match/${newMatchId}`);

    } catch (err) {
      console.error("Error creating match", err);
      setError("Failed to create match. Please try again.");
      setIsSubmitting(false);
    }
  };

  // 4. Render the UI
  return (
    <Container className="py-5">
      <Row className="justify-content-center">
        <Col md={8} lg={6}>
          <Card className="shadow-sm border-0">
            <Card.Body className="p-4">
              <h3 className="fw-bold mb-4">Pre-Match Setup</h3>
              
              {error && <Alert variant="danger">{error}</Alert>}

              {/* Show a spinner while fetching teams from the API */}
              {isLoading ? (
                <div className="text-center py-5">
                  <Spinner animation="border" variant="success" />
                  <p className="text-muted mt-3">Loading teams...</p>
                </div>
              ) : (
                <Form onSubmit={handleSubmit}>
                  
                  <Form.Group className="mb-3">
                    <Form.Label className="fw-semibold">Tournament / League Name</Form.Label>
                    <Form.Control 
                      type="text" 
                      placeholder="e.g., Division 1 League" 
                      value={tournamentName}
                      onChange={(e) => setTournamentName(e.target.value)}
                    />
                  </Form.Group>

                  <Row>
                    <Col md={6}>
                      <Form.Group className="mb-4">
                        <Form.Label className="fw-semibold">Home Team</Form.Label>
                        <Form.Select 
                          value={homeTeamId} 
                          onChange={(e) => setHomeTeamId(e.target.value)}
                          required
                        >
                          <option value="" disabled>Select Home Team</option>
                          {teams.map((team) => (
                            <option key={team.id} value={team.id}>
                              {team.name} {team.isOurTeam ? "(Ours)" : ""}
                            </option>
                          ))}
                        </Form.Select>
                      </Form.Group>
                    </Col>
                    
                    <Col md={6}>
                      <Form.Group className="mb-4">
                        <Form.Label className="fw-semibold">Away Team</Form.Label>
                        <Form.Select 
                          value={awayTeamId} 
                          onChange={(e) => setAwayTeamId(e.target.value)}
                          required
                        >
                          <option value="" disabled>Select Away Team</option>
                          {teams.map((team) => (
                            <option key={team.id} value={team.id}>
                              {team.name}
                            </option>
                          ))}
                        </Form.Select>
                      </Form.Group>
                    </Col>
                  </Row>

                  <div className="d-grid gap-2">
                    <Button 
                      variant="success" 
                      size="lg" 
                      type="submit"
                      disabled={isSubmitting || teams.length < 2}
                    >
                      {isSubmitting ? 'Preparing Pitch...' : 'Proceed to Touchline Dashboard'}
                    </Button>
                    
                    {/* Helper text if they haven't created enough teams in the database yet */}
                    {teams.length < 2 && (
                      <Form.Text className="text-danger text-center mt-2">
                        You need at least 2 teams in the system to start a match.
                      </Form.Text>
                    )}
                  </div>
                </Form>
              )}
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </Container>
  );
};

export default NewMatch;